table Medidas
	lineageTag: aae5768b-12ad-435f-844d-dfe78ea810ed

	measure 'R$ Margem' = [R$ Receita] - [R$ Custos]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a61ef6ee-3efe-4339-9007-8dc0a35986b8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Custos' = Sumx(Vendas, Vendas[Quantidade] * RELATED(Produtos[CustoUnitario]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: fc1a922d-b841-42b7-93dc-04366f34ecfb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Receita' = Sum(Vendas[Receita])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: fcc15c65-b994-49ed-837f-bdb30eb8be84

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

